### ISSUE TITLE
Build&Compile Problem

### ISSUE THREAD

**Issue by erkutgenc** [jbruening/PclSharp#2]
I write a thesis on lidar data. c ++ is a difficult language for me because I usually use Matlab. I need to analyze and process the data. But some .tt files in the solution are not working well and I realized that they do not produce some files. I am waiting for your help with the topic. thanks for your interest.

**Comment by jbruening** [comment]
I've been debating including the files generated from the text templates. I'll do that when I can.

**Comment by jbruening** [comment]
The generated files are now included in the repository with 99870e4, and I've removed the line in gitignore so future files will be there
