### ISSUE TITLE
NormalEstimation missing?

### ISSUE THREAD

**Issue by Abstractmachina** [jbruening/PclSharp#20]
Hi, 
Sry if this is a beginner question, im generally new to the point cloud library so might have missed smt. I'm trying to compute the surface normals of a point cloud, and in the cpp documentation, a NormalEstimation class is used for that purpose. I've combed through the PclSharp library but couldnt find anything that seems to be equivalent. It's hard to imagine that something as fundamental as normal calculation is missing, so I figured maybe its buried somewhere in the code. 
Im using unstructured point clouds, so AFAIK i cant use the IntegralImageNormalEstimation either. Thx in advance!

**Comment by jbruening** [comment]
If you're unable to find classes in the library, it's likely no bindings have been made yet. This library is incomplete, and you should be able to add your own bindings to the classes you need. See some of the existing class bindings for direction, or look at other package forks to see if they have it.
