### ISSUE TITLE
some ref value problem & Winform Implementation

### ISSUE THREAD

**Issue by erkutgenc** [jbruening/PclSharp#3]
thanks for your help. I compiled updated source today and some "ref" values make a problem.
for example 
namespace PclSharp
{
    public abstract class PointCloud<PointT> : UnmanagedObject
    {
        public abstract int Width { get; set; }
        public abstract int Height { get; set; }
        public abstract bool IsDense { get; set; }
        public abstract Vector<PointT> Points { get; }
        public abstract int Count { get; }
        public abstract bool IsOrganized { get; }

        """public abstract ref PointT At(int col, int row);""" -> ref value problem
        public abstract void Add(PointT value);
    }

I unloaded some parts of code which I didn't need to use after source compiled. but this time, i couldn't implement with winform interface. I tried some solutions with vtk based but I couldn't be successful. 

I will be very pleased if you can help. thanks for your valuable help.

**Comment by jbruening** [comment]
This is a [csharp 7 feature](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/ref-returns). Make sure you're using visual studio 2017.
