### ISSUE TITLE
c++ dll didn't work on x86 platform

### ISSUE THREAD

**Issue by erkutgenc** [jbruening/PclSharp#4]
Hi,
c++ dlls (pclsharp.extern.dll and pclsharp.externvis.dll) compile x86 platform but I couldn't run this dll. I try some solution but i haven't succeeded. I am waiting for your help with the topic. thanks for your interest.
Some Info :
My problem is access violation. 
I use pcl 1.8.1(win32 - release) all in one package. I'm sure pcl and other library released on win32 platform.

**Comment by tohuuduc** [comment]
I have the same issue. Installed Nuget package and try this project to understand how it works. But it requires pclsharp.extern.dll. No such file in the package.

**Comment by jbruening** [comment]
I don't have an x86 version at this time. Someone is welcome to submit a pull request with support for it.
