### ISSUE TITLE
DLLNotFoundException

### ISSUE THREAD

**Issue by vasadhananjay** [jbruening/PclSharp#5]
I wrote a quick test application which reads in a point cloud text file and tries to store it inside of a PointCloudOfXYZ. When I call the constructor for PointCloudOfXYZ it, I'm getting a DLLNotFoundException for PclSharp.Extern.dll. Not sure why the DLLImport can't find the file. This is running the x64 debug/release versions.

**Comment by jbruening** [comment]
You're probably missing things like having pcl installed in your path. Make sure it can find the dlls it needs by loading the extern dll in a tool like [dependency walker](http://www.dependencywalker.com/)

**Comment by vasadhananjay** [comment]
Thanks! Yeah. There was a missing dependency from Windows oddly enough. Ran CCleaner's registry cleaner and it seemed to resolve it.
