### ISSUE TITLE
Getting invalid token 'ref' errors on compile

### ISSUE THREAD

**Issue by jmaeding** [jbruening/PclSharp#7]
I'm seeing a bunch of these such as in file ConvexHullOfXYZ.generated.cs, line 72.
I am using vs2015, but I compile .net 4.7 framework projects all the time.
I looked up using ref like it is, and I did not see anything sayin that was a valid use, like:
public override ref PointXYZ this[int idx]
Is this something in progress, or is there a setting I need to touch to allow it?

**Comment by jbruening** [comment]
It's a c#7 feature. As per the second line in the [readme](https://github.com/jbruening/PclSharp/blob/master/README.md), this project requires vs2017 to compile.
